### PR TITLE
Simplier package description.

### PR DESCRIPTION
**Pull request by amatkivskiy**

### CODE REVIEW

**Comment by Odonno** [comment]
Good !

I think the page description should be consistent.
Could you change file with shorter description on all packages, including mines ?

**Comment by amatkivskiy** [comment]
@Odonno done.

**Comment by Odonno** [comment]
Nice !

**Comment by Odonno** [comment]
Oh, just see your PR does not target the right branch. My current PR branch used in https://github.com/gitterHQ/docs/pull/8 is Odonno:packages.

**Comment by amatkivskiy** [comment]
Sorry, my mistake(

**Comment by Odonno** [comment]
How can we fix that ?

**Comment by amatkivskiy** [comment]
as far as I know you can rebase you master branch to the previous commits and that I will create proper pull request.

**Comment by Odonno** [comment]
I reverted your code on branch master. Can you make `git pull` on branch packages and pushing your changes on this branch ?

Thank you.

**Pull request merged**
